name = "website-worker"
main = "./dist-worker/worker.mjs"
compatibility_date = "2025-10-07"

# Production routes
routes = [
  { pattern = "cloudcache.ai/*", zone_name = "cloudcache.ai" },
  { pattern = "www.cloudcache.ai/*", zone_name = "cloudcache.ai" }
]

[site]
  bucket = "./dist"

# Staging environment
[env.staging]
name = "website-worker-staging"
main = "./dist-worker/worker.mjs"
routes = [
  { pattern = "staging-website.cloudcache.ai/*", zone_name = "cloudcache.ai" }
]

# Preview environment
[env.preview]
name = "website-worker-preview"
main = "./dist-worker/worker.mjs"
workers_dev = true
routes = []
