# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "SHOPIFY_API_KEY"
name = "CloudCache ShopApp"
application_url = "https://app.cloudcache.ai"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cloudcache-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,write_draft_orders"

[auth]
redirect_urls = [
  "https://app.cloudcache.ai/auth/callback",
  "https://app.cloudcache.ai/auth/shopify/callback",
  "https://app.cloudcache.ai/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["shop/update"]
uri = "/webhooks"

[pos]
embedded = false
