# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Secrets Scan
on:
  pull_request:

env:
  ENABLE_SECRETS_SCAN: ${{ vars.ENABLE_SECRETS_SCAN || 'true' }}

jobs:
  gitleaks:
    if: ${{ env.ENABLE_SECRETS_SCAN != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true
      - name: Summary
        run: |
          {
            echo "### Secrets Scan toggles";
            echo "- ENABLE_SECRETS_SCAN=${{ env.ENABLE_SECRETS_SCAN }}";
          } >> "$GITHUB_STEP_SUMMARY"

